data:
  file_path: "C:\\Users\\Startklar\\DATA\\phising-website-detection\\data\\phising.csv"
  target_column: "Result"
  test_size: 0.2
  random_state: 42

artifacts:
  directory: "artifacts"
  scaler_filename: "scaler.pkl"
  xgb_model_filename: "xgb_model.pkl"
  ann_model_filename: "ann_mlp_model.pkl"


scaler:
  type: "StandardScaler" 

xgboost:
  n_estimators: 400
  max_depth: 7
  learning_rate: 0.04
  subsample: 0.9
  colsample_bytree: 0.9
  gamma: 0.2
  min_child_weight: 3
  reg_alpha: 0.3
  reg_lambda: 1.0
  scale_pos_weight: 1
  n_jobs: -1
  eval_metric: "logloss"

# ========================
# ANN (MLPClassifier) CONFIG
# ========================
mlp: # multi-layer perceptron
  hidden_layers: [128, 64, 32]
  activation: "relu"
  solver: "adam"
  learning_rate_init: 0.001
  alpha: 0.0005
  batch_size: 64
  max_iter: 400
  early_stopping: true
  validation_fraction: 0.1